name: github-action-test

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        id: commit
        uses: prompt/actions-commit-hash@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.NCR_URL }}
          username: ${{ secrets.NCR_ID }}
          password: ${{ secrets.NCR_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.NCR_URL }}/app1:${{ steps.commit.outputs.short }}
      - 
        name: deployment
        uses: tale/kubectl-action@v1        
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
      - run: |
          kubectl set image deployment/test1-deployment test=${{ secrets.NCR_URL }}/app1:${{ steps.commit.outputs.short }}
          kubectl rollout status deployment/test1-deployment
      
  push:
    name: Push Manifest
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: git push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config credential.helper store
          git add argocd/test.yml
          git commit -m ":tada: Update: Image [${{ steps.commit.outputs.short }}]"
          git push
